### ISSUE TITLE
jquery selector typo and not good enough

### ISSUE THREAD

**Issue by ganlvtech** [Anduin2017/jquery-anything-clickable#1]
https://github.com/Anduin2017/jquery-anything-clickable/blob/a3743618d0a1b2827581b1615074ad4746cdafb7/src/jquery-anything-clickable.js#L2

* [ ] missing bracket `]`
* [ ] no need to add a `*`

**Comment by Anduin2017** [comment]
Thanks for your contribution! Resolved in pull request #2.
